### ISSUE TITLE
genlouvain vs bct. community_louvain

### ISSUE THREAD

**Issue by Pulkit-Khandelwal** [nangongwubu/Python-Version-for-Network-Community-Architecture-Toobox#1]
The `genlouvain` is same as `bct. community_louvain`. In the original matlab toolbox for network community http://commdetect.weebly.com/, `genlouvain.m` is mentioned but never called; instead `bct. community_louvain` is used. Has `genlouvain.m` been removed or deprecated to `bct. community_louvain`?

**Comment by xdjwolf** [comment]
There‘s a question about bct in nact.py , "import bct ",but I didn't find any module name bct when excute pip install  --user bct.
How can I solve  this problem?

**Comment by Pulkit-Khandelwal** [comment]
Nevermind, I got the solution. Thanks!
